### ISSUE TITLE
Parallelism in icepack and Firedrake

### ISSUE THREAD

**Issue by bryanvriel** [icepack/icepack#105]
What is the canonical way to exploit parallelism in icepack/Firedrake/PETSc? Both the Firedrake and PETSc documentation recommend using only the MPI scheduler (`mpirun`) instead of utilizing multithreading (presumably via BLAS or OpenMP?), which makes sense. However, my hunch is that it's not as straightforward as simply calling `mpirun` on a Python script (which I tried and failed to see any speedup). Do we need to add our own MPI code, or is most of the distributed processing built into the Firedrake routines?

**Comment by danshapero** [comment]
Hey Brian -- at least at the outer level, the only difference is doing `mpiexec -n <num procs> python simulation.py`. As for threads, my understanding is that PETSc [doesn't use them](https://petsc.org/release/miscellaneous/threads/) because the developers consider doing everything with MPI to be easier at the end of the day.

What solver options are you passing to PETSc? If you're just using the defaults, I wrote a bit about how to pass different solver options to PETSc in [this notebook](https://icepack.github.io/notebooks/how-to/01-performance/). The default solver options that icepack uses are biased heavily towards something that will converge with as little tweaking on the user's part as possible. If you're looking at bigger problems and speed is becoming important, you'll want to switch to CG or GMRES for the outer-level iterative solver and probably either an alternating Schwarz method or multigrid for the inner-level solver.

If you can link here or send me the code that you're wanting to parallelize then I can play around with it myself.

**Comment by bryanvriel** [comment]
Thanks for the info @danshapero! That notebook was very helpful, especially the part about using different solvers for different stages of the simulation. At the end of the day, it turned out that I was using the `mpiexec` installed by homebrew rather than the `mpiexec` built during the PETSc installation. By using the latter, I can now see a speed-up when using `num_procs` > 1 (sub-linear speedup, but that's fine).

**Comment by danshapero** [comment]
Gotcha, glad it was helpful. I suspect that passing some different options for the prognostic solve might further improve on things, but that can be a little less straightforward because the mass conservation equation isn't positive-definite like the momentum equation.

All the same, we could probably be better about parallel scaling. Let me know if it does become a limiting factor and I can try a few more things.
